name: darmbank
description: Um aplicativo de banco digital.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: "^0.11.0"

  get: ^4.6.5
  mobx:
  flutter_mobx:

  http: ^0.13.5
  flutter_svg: ^1.1.6

dev_dependencies:
  
  flutter_test:
    sdk: flutter
  integration_test:           # new
    sdk: flutter              # new
  test: ^1.14.4               # new

  mobx_codegen:
  build_runner:
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

# Meus recursos
  assets:
    - assets/images/
    - assets/icons/

# Minhas fontes
  fonts:
    - family: Montserrat
      fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
      - asset: assets/fonts/Montserrat-SemiBold.ttf
        #weight: 700
      - asset: assets/fonts/Montserrat-ExtraBold.ttf
    - family: Poppins
      fonts:
      - asset: assets/fonts/Poppins-Regular.ttf

# Icone do APP
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#9747FF"

# Splashscreen
flutter_native_splash:
  color: "#9747FF"
  image: assets/images/icon_app.png
  android: true
  ios: true
  web: false
  android_12:
    image: assets/images/icon_app.png
    icon_background_color: "#9747FF"
